import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Link from "next/link";
import Table from "@/components/Table";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="container my-5">
                <div className="columns is-vcentered mb-6 mx-5">
                    <div className="column table-container has-background-link-dark animate__animated animate__fadeIn">
                        <Table />
                        {/* <div
                            className="card-header has-background-link-light"
                            style={{ borderRadius: "3px" }}
                        >
                            <p className="card-header-title is-size-4">
                                Menu Toko
                            </p>
                        </div>
                        <div className="card-content">
                            <div className="tile is-ancestor">
                                <div className="tile is-vertical is-parent">
                                    <Link
                                        id="tombol-lihat-stok-homepage"
                                        className="tile is-child box has-background-link-light"
                                        href={"/item"}
                                    >
                                        <p className="title has-text-link-dark">
                                            Lihat Item
                                        </p>
                                        <p className="subtitle">
                                            Melihat, mengubah, dan menghapus
                                            item
                                        </p>
                                    </Link>
                                    <Link
                                        id="tombol-tambah-stok-homepage"
                                        className="tile is-child box has-background-link-light"
                                        href={"/item/create"}
                                    >
                                        <p className="title has-text-link-dark">
                                            Tambah Item
                                        </p>
                                        <p className="subtitle">
                                            Menambahkan item baru
                                        </p>
                                    </Link>
                                </div>
                                <div className="tile is-vertical is-parent">
                                    <Link
                                        id="tombol-jual-item-homepage"
                                        className="tile is-child box has-background-link-light"
                                        href={"/item/sell"}
                                    >
                                        <p className="title has-text-link-dark">
                                            Jual Item
                                        </p>
                                        <p className="subtitle">
                                            Melakukan proses penjualan
                                        </p>
                                    </Link>
                                    <Link
                                        id="tombol-summary-homepage"
                                        className="tile is-child box has-background-link-light"
                                        href={"/penjualan"}
                                    >
                                        <p className="title has-text-link-dark">
                                            Summary
                                        </p>
                                        <p className="subtitle">
                                            Melihat summary penjualan
                                        </p>
                                    </Link>
                                </div>
                            </div>
                        </div> */}
                    </div>
                </div>
            </div>
            <Footer />
        </>
    );
}
